feat: [P4PU-173] login apge
pagopa/pagopa-arc-fe pull request #49
Opened 2024-06-12 12:13 UTC by AnisLucidi01

#### List of Changes

Created static page for login

#### Motivation and Context

This change is required by design
#### How Has This Been Tested?
Visual testing and Jest.

#### Screenshots (if appropriate):
![image](https://github.com/pagopa/pagopa-arc-fe/assets/125553099/5d4e1f4c-486e-48ee-9de7-040127ea3b9d)

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-12 15:05 UTC, stratoivandiluccio commented
I found some missing elements in the footer and inconsistencies with the design. Please check again

2024-06-12 15:06 UTC, stratoivandiluccio requested changes
I found some missing elements in the footer and inconsistencies with the design. Please check again

2024-06-12 18:12 UTC, AnisLucidi01 commented
@stratoivandiluccio I've fixed the issues, please let me know if it's okay.

2024-06-13 07:11 UTC, stratoivandiluccio approved these changes

2024-06-13 07:48 UTC, merged