feat: P4ADEV-166 Implemented footer
pagopa/pagopa-arc-fe pull request #6
Opened 2024-04-12 08:40 UTC by AnisLucidi01

#### List of Changes

Added and configured footer component from MUI Italia, and adapted languages file for it.

#### How Has This Been Tested?

Visual testing.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-04-16 09:52 UTC, stratoivandiluccio commented on src/components/Layout.tsx
> +          <Footer
Could you restore the Footer.tsx file and write an own Footer component that return the mui Footer component configured like that?

2024-04-16 09:55 UTC, stratoivandiluccio commented on src/App.tsx
> +  };
Please move this logic in an external hook so you can write some unit test easily

2024-04-16 10:51 UTC, stratoivandiluccio requested changes
I added some feedback as comment

2024-04-16 13:15 UTC, stratoivandiluccio commented on src/components/Layout.tsx
> +      maxWidth={false}
It's ok for now to have the footer non stretching the whole page width. You should just restore 'lg' and doing nothing else

2024-04-18 13:06 UTC, mmoio approved these changes

2024-04-18 13:08 UTC, merged