feat: [P4PU-162] transaction detail api adaptation
pagopa/pagopa-arc-fe pull request #69
Opened 2024-07-04 09:22 UTC by AnisLucidi01

#### List of Changes
Adapted new API for transaction details. 

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-04 16:05 UTC, stratoivandiluccio commented on src/routes/Transaction.tsx
>  // import TransactionDetail from '../components/Transactions/TransactionDetail';
remove this unuseful commented line

2024-07-04 19:18 UTC, AnisLucidi01 commented on src/utils/converters.test.ts
> +    expect(utils.converters.toEuro(0)).toEqual('-');
With Roberto we decided to convert 0€ to "-", as per task P4PU-256

2024-07-05 07:16 UTC, stratoivandiluccio commented on src/utils/converters.test.ts
> +    expect(utils.converters.toEuro(0)).toEqual('-');
Sorry, but can't work in this way. At least we can return '-' when the function receive undefined, not 0.

2024-07-08 07:20 UTC, mmoio approved these changes

2024-07-08 07:36 UTC, stratoivandiluccio commented on src/routes/Transaction.tsx
>          fallback={isError && <p>Ops! Something went wrong, please try again</p>}
This component (QueryLoader) doesn't accept a fallback property anymore

2024-07-08 07:39 UTC, stratoivandiluccio requested changes
Please check the QueryLoader in src/routes/Transaction

2024-07-08 07:54 UTC, stratoivandiluccio approved these changes

2024-07-08 08:05 UTC, merged